# Embeds logo.png (or the file given) into logo.js as a base64 data URL,
# so the logo works offline and inside exported reports.
param(
  [string]$Path = "$PSScriptRoot\logo.png",
  # Fraction of the image kept (center crop). Below 1 trims a white ring around round photos.
  [double]$Zoom = 0.86
)

Add-Type -AssemblyName System.Drawing
if (-not (Test-Path $Path)) { Write-Error "Logo not found: $Path"; exit 1 }

# Resize to 160x160 (center crop) to keep the app and reports small.
$src = [System.Drawing.Image]::FromFile((Resolve-Path $Path))
$size = 160
$side = [int]([Math]::Min($src.Width, $src.Height) * $Zoom)
$bmp = New-Object System.Drawing.Bitmap $size, $size
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.InterpolationMode = 'HighQualityBicubic'
$g.DrawImage($src, (New-Object System.Drawing.Rectangle 0, 0, $size, $size),
  (New-Object System.Drawing.Rectangle ([int](($src.Width - $side) / 2)), ([int](($src.Height - $side) / 2)), $side, $side),
  [System.Drawing.GraphicsUnit]::Pixel)
$ms = New-Object System.IO.MemoryStream
$jpg = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq "image/jpeg" }
$ep = New-Object System.Drawing.Imaging.EncoderParameters 1
$ep.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter ([System.Drawing.Imaging.Encoder]::Quality), 90L
$bmp.Save($ms, $jpg, $ep)
$g.Dispose(); $bmp.Dispose(); $src.Dispose()

$b64 = [Convert]::ToBase64String($ms.ToArray())
$js = "// Generated by make-logo.ps1`nwindow.APP_LOGO = 'data:image/jpeg;base64,$b64';`n"
[System.IO.File]::WriteAllText("$PSScriptRoot\logo.js", $js, (New-Object System.Text.UTF8Encoding $false))
Write-Host "logo.js updated ($([Math]::Round($b64.Length / 1024)) KB)"
