# Embeds logo.png (or the file given) into logo.js as a base64 data URL,
# so the logo works offline and inside exported reports.
param([string]$Path = "$PSScriptRoot\logo.png")

Add-Type -AssemblyName System.Drawing
if (-not (Test-Path $Path)) { Write-Error "Logo not found: $Path"; exit 1 }

# Resize to 256x256 (center crop) to keep the app and reports small.
$src = [System.Drawing.Image]::FromFile((Resolve-Path $Path))
$size = 256
$side = [Math]::Min($src.Width, $src.Height)
$bmp = New-Object System.Drawing.Bitmap $size, $size
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.InterpolationMode = 'HighQualityBicubic'
$g.DrawImage($src, (New-Object System.Drawing.Rectangle 0, 0, $size, $size),
  (New-Object System.Drawing.Rectangle ([int](($src.Width - $side) / 2)), ([int](($src.Height - $side) / 2)), $side, $side),
  [System.Drawing.GraphicsUnit]::Pixel)
$ms = New-Object System.IO.MemoryStream
$bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
$g.Dispose(); $bmp.Dispose(); $src.Dispose()

$b64 = [Convert]::ToBase64String($ms.ToArray())
$js = "// Generated by make-logo.ps1`nwindow.APP_LOGO = 'data:image/png;base64,$b64';`n"
[System.IO.File]::WriteAllText("$PSScriptRoot\logo.js", $js, (New-Object System.Text.UTF8Encoding $false))
Write-Host "logo.js updated ($([Math]::Round($b64.Length / 1024)) KB)"
